# Generated by Django 5.2.1 on 2025-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('anio_publicacion', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
