# Generated by Django 5.2.1 on 2025-05-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
