# Generated by Django 5.2.1 on 2025-05-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad disponible'),
        ),
    ]
